spring.application.name=tournament

spring.datasource.url=jdbc:postgresql://localhost:5432/chess_tournament
spring.datasource.username=chess
spring.datasource.password=chess

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
